### ISSUE TITLE
Erratic memory usage

### ISSUE THREAD

**Issue by laserkelvin** [kncrabtree/blackchirp#17] opened 2019-03-01 21:12 UTC
There are periods of integration where the computer grinds to a halt, and top (image below) reveals that the memory usage of blackchirp is through the roof.

This occurred just prior to restarting the computer, and only Firefox and blackchirp are open.

![2019-03-01](https://user-images.githubusercontent.com/17684745/53666677-c60dac80-3c3c-11e9-8e7d-09d0bb6b803c.jpg)

**Comment by kncrabtree** [comment] 2019-03-01 21:30
Yeah, that would be a problem. Was it just sitting idle? What had you done in the program up to that point?

**Comment by laserkelvin** [comment] 2019-03-01 22:08
It just collected about ~11k shots, not averaging frames (10 frames). Anything you could recommend to help diagnose the problem?

**Comment by kncrabtree** [comment] 2019-03-01 22:11
If you can trigger this reproducibly, then do it while running valgrind and then let me look through the output. That'll help me track the memory leak

**Comment by laserkelvin** [comment] 2019-03-05 16:31
Haven't had a change to run it with valgrind yet, but in the interrim we've found two things according to Brett that trigger the memory usage:

1. When you mouse wheel change through individual frames
2. When you repeatedly run peak up mode; each time increments the memory usage by ~5% and does not get reduced until the program is reset

Do you want valgrind run any particular way? What output, etc.?

**Comment by kncrabtree** [comment] 2019-03-05 16:39
Ok, I'll take a look at those things as soon as I get the chance. When you're running peak-up mode, this is also with individual frames enabled?

As for valgrind, I think the standard output (as displayed in qt creator) should make the problem obvious.

**Comment by kncrabtree** [comment] 2019-03-29 16:36
So far I have been unable to reproduce this issue, though I've been testing on the segmented branch. I have not tried the master branch. I suspect the memory leak is in the FtmwViewWidget in the master branch, but that code has been completely rewritten in the segmented branch with more robust data structures and processing mechanics. It is my intention to merge the segmented branch into the master branch, which I expect will resolve this issue. Are you all prepared for me to do that? I know you were testing out the segmented branch a while ago, did you change back? If so, are there changes you need in the segmented branch?

**Comment by kncrabtree** [comment] 2021-05-18 16:43
Closing this issue. There have been no reports of this memory leak since the segmented branch was merged into master.

**Closed as completed by kncrabtree** 2021-05-18 16:43 UTC
